import os
import json
import uuid
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv
import re
import math

load_dotenv()

app = Flask(__name__)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# Audit log helpers

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# Signal 1: LLM-based classification 

def get_llm_score(text):
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return ONLY a valid JSON object with exactly two fields:
- "score": a float from 0.0 (clearly human-written) to 1.0 (clearly AI-generated)
- "rationale": a string (in double quotes) with one sentence explaining your assessment

Example of valid output:
{{"score": 0.85, "rationale": "The text uses uniform sentence structure typical of AI generation."}}

Text to analyze:
\"\"\"
{text}
\"\"\"

Respond with ONLY the JSON object. Both values must be properly quoted. No explanation, no markdown."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    raw = re.sub(r"```json|```", "", raw).strip()

    # extract score directly with regex as fallback
    score_match = re.search(r'"score"\s*:\s*([0-9.]+)', raw)
    rationale_match = re.search(r'"rationale"\s*:\s*"?([^"}\n]+)"?', raw)

    if score_match:
        score = float(score_match.group(1))
        score = max(0.0, min(1.0, score))
        rationale = rationale_match.group(1).strip() if rationale_match else ""
        return score, rationale

    return 0.5, "Could not parse LLM response"


# Signal 2: Stylometric heuristics

def get_stylometric_score(text):
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = text.split()

    if len(sentences) < 2 or len(words) < 10:
        return 0.5

    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    variance_score = max(0.0, min(1.0, 1 - (std_dev / 15)))

    unique_words = set(w.lower().strip('.,!?;:"\'') for w in words)
    ttr = len(unique_words) / len(words)
    ttr_score = max(0.0, min(1.0, 1 - ((ttr - 0.3) / 0.6)))

    informal_punct = len(re.findall(r'[—–\-…]|\.\.\.', text))
    punct_per_word = informal_punct / len(words)
    punct_score = max(0.0, min(1.0, 1 - (punct_per_word * 20)))

    combined = (variance_score * 0.4) + (ttr_score * 0.4) + (punct_score * 0.2)
    return round(combined, 4)


# Confidence scoring

def get_confidence_score(llm_score, stylometric_score):
    return round((0.6 * llm_score) + (0.4 * stylometric_score), 4)


# Label generation 

def get_label(confidence):
    if confidence >= 0.65:
        attribution = "likely_ai"
        label = (
            "This content shows strong signals of AI generation. "
            "Our system detected patterns consistent with AI-generated text with high confidence."
        )
    elif confidence <= 0.35:
        attribution = "likely_human"
        label = (
            "This content shows strong signals of human authorship. "
            "Our system detected patterns consistent with human-written text with high confidence."
        )
    else:
        attribution = "uncertain"
        label = (
            "We can't confidently determine whether this content is AI-generated or human-written. "
            "This label reflects genuine uncertainty in our detection signals — it is not an accusation."
        )
    return attribution, label


# Routes 

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id'"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score, rationale = get_llm_score(text)
    stylometric_score = get_stylometric_score(text)
    confidence = get_confidence_score(llm_score, stylometric_score)
    attribution, label = get_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "llm_rationale": rationale,
        "stylometric_score": stylometric_score,
        "status": "classified",
        "appeal": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Request must include 'content_id' and 'creator_reasoning'"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    entries = read_log()
    found = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal"] = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "creator_reasoning": reasoning,
            }
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found"}), 404

    write_log(entries)

    return jsonify({
        "message": "Appeal received. Your submission has been marked for human review.",
        "content_id": content_id,
        "status": "under_review",
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries})


if __name__ == "__main__":
    app.run(debug=True)